# Generated by Django 5.1.5 on 2025-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="cv_file",
            field=models.FileField(blank=True, null=True, upload_to="CVs/"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
