# Generated by Django 5.1.5 on 2025-02-26 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.AlterModelOptions(
            name="interview",
            options={"ordering": ["-scheduled_date"]},
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="mobile",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="mobile",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="created_on",
        ),
        migrations.AddField(
            model_name="candidate",
            name="candidate_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("neutral", "Passive"),
                    ("inactive", "Not Looking"),
                    ("under_Offer", "Offered"),
                    ("Placed", "Placed"),
                    ("no_contact", "Do not contact"),
                ],
                default="active",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="prefs",
            field=models.CharField(
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Freelance", "Freelance"),
                ],
                default="Freelance",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="salary",
            field=models.DecimalField(
                decimal_places=2, default=django.utils.timezone.now, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interview",
            name="job_spec",
            field=models.FileField(blank=True, null=True, upload_to="interview_specs/"),
        ),
        migrations.AddField(
            model_name="interview",
            name="pdf_guides",
            field=models.FileField(
                blank=True, null=True, upload_to="interview_guides/"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="commission_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="job",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="app_status",
            field=models.CharField(
                choices=[
                    ("Review", "Review"),
                    ("Suitable", "Suitable"),
                    ("Rejected", "Rejected"),
                    ("Longlist", "Longlist"),
                    ("Shortlist", "Shortlist"),
                ],
                default="Review",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="placement",
            name="commission_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="placement",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recruitment.company",
            ),
        ),
        migrations.AddField(
            model_name="placement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="placement",
            name="day_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="placement",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="placement_type",
            field=models.CharField(
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Freelance", "Freelance"),
                ],
                default="Freelance",
                max_length=15,
            ),
        ),
    ]
