# Generated by Django 5.1.5 on 2025-02-26 20:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("sender", models.EmailField(max_length=254)),
                ("recipient", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("urgent_important", "Urgent & Important"),
                            ("important_not_urgent", "Important, Not Urgent"),
                            ("urgent_not_important", "Urgent, Not Important"),
                            ("not_urgent_not_important", "Not Urgent, Not Important"),
                        ],
                        default="not_urgent_not_important",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="task",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="due_by",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 28, 20, 3, 33, 404609, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="follow_up_after",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_do", "To Do"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                ],
                default="to_do",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.email",
            ),
        ),
    ]
